services:
  akvatar:
    image: ghcr.io/patschi/akvatar:latest
    container_name: akvatar
    restart: unless-stopped
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    tmpfs:
      - /tmp
    ports:
      - "5000:5000"
    volumes:
      - akvatar-conf:/data/config:ro
      - akvatar-data:/data/user-avatars

volumes:
  akvatar-data:
  akvatar-conf:
