services:
  akvatar:
    build: .
    container_name: akvatar
    restart: no
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    tmpfs:
      - /tmp
    environment:
      - DEBUG_MODE=true
    ports:
      - "5000:5000"
    volumes:
      - ./data/config:/data/config:ro
      - ./data/user-avatars:/app/data/user-avatars
